[project]
name = "3-perf-compare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backtesting>=0.6.5",
    "backtrader>=1.9.78.123",
    "backtrader-next>=2.1.1",
]
